[tox]
isolated_build = True
envlist =
    py{38,39,310,311,312,313,314}-django{32,42},
    py{310,311,312,313,314}-django{52}

[testenv]
commands = python -m coverage run --parallel -m pytest {posargs:tests}
deps =
    -r requirements/{envname}.txt

[testenv:py38]
deps =
    -r https://raw.githubusercontent.com/DLRSP/requirements/main/py38-dev.txt

[testenv:py39]
deps =
    -r https://raw.githubusercontent.com/DLRSP/requirements/main/py39-dev.txt

[testenv:py310]
deps =
    -r https://raw.githubusercontent.com/DLRSP/requirements/main/py310-dev.txt

[testenv:py311]
deps =
    -r https://raw.githubusercontent.com/DLRSP/requirements/main/py311-dev.txt

[testenv:py312]
deps =
    -r https://raw.githubusercontent.com/DLRSP/requirements/main/py312-dev.txt

[testenv:py313]
deps =
    -r https://raw.githubusercontent.com/DLRSP/requirements/main/py313-dev.txt

[testenv:py314]
deps =
    -r https://raw.githubusercontent.com/DLRSP/requirements/main/py314-dev.txt
